ktor:
  application:
    modules:
      - com.collektar.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

spotify:
  clientId: ${SPOTIFY_CLIENT_ID}
  clientSecret: ${SPOTIFY_CLIENT_SECRET}
  baseUrl: "https://api.spotify.com/v1"
  tokenUrl: "https://accounts.spotify.com/api/token"
  defaultPlaylistId: "5iwkYfnHAGMEFLiHFFGnP4" # Todays Top Hits Playlist