---
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  #websecure:
    #address: ":443"
  traefik:
    address: ":8080"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

#certificatesResolvers:
  #le:
    #acme:
      #email: mail@localhost.com
      #storage: /letsencrypt/acme.json
      #dnsChallenge:
        #provider: cloudflare
        #delayBeforeCheck: 0

log:
  level: INFO
