---
networks:
  #
  # Definition of the shared network
  #
  media-network:
    driver: bridge
services:
  #
  # Reverse Proxy / API-Gateway
  #
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_HTTPS_PORT}:443"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./backend/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./backend/traefik/dynamic:/etc/traefik/dynamic:ro
    networks:
      - media-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
  #
  # Authentication- and User-Service
  #
  auth-service:
    build:
      context: ./backend/Authentication-Service/
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      - DB_URL=jdbc:postgresql://auth-db:5432/${AUTH_DB_NAME}
      - DB_USER=${AUTH_DB_USER}
      - DB_PASSWORD=${AUTH_DB_PASSWORD}
    user: "1000:1000"
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - media-network
    volumes:
      - ./secrets/jwt_private.pem:/run/secrets/jwt_private.pem:ro
      - ./config/jwt_public.pem:/run/config/jwt_public.pem:ro
      - ./secrets/token_hasher_secret:/run/secrets/token_hasher_secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      # HTTP Router
      - "traefik.http.routers.auth.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.service=auth-service"
      # Service definition
      - "traefik.http.services.auth-service.loadbalancer.server.port=8080"
      # Middleware to strip /api/auth prefix
      - "traefik.http.middlewares.auth-stripprefix.stripprefix.prefixes=/api/auth"
      - "traefik.http.routers.auth.middlewares=auth-stripprefix"
  #
  # Service to manage user collections
  #
  collection-service:
    build:
      context: ./backend/Collection-Service/
      dockerfile: Dockerfile
    container_name: collection-service
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - DB_URL=jdbc:postgresql://collection-db:5432/${COLLECTION_DB_NAME}
      - DB_USER=${COLLECTION_DB_USER}
      - DB_PASSWORD=${COLLECTION_DB_PASSWORD}
    depends_on:
      collection-db:
        condition: service_healthy
    networks:
      - media-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collection.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/collection`)"
      - "traefik.http.routers.collection.entrypoints=web"
      - "traefik.http.routers.collection.service=collection-service"
      - "traefik.http.services.collection-service.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.collection-stripprefix.stripprefix.prefixes=/api/collection"
      - "traefik.http.routers.collection.middlewares=auth-forward@file,collection-stripprefix"
  #
  # Service to interface and handle external APIs
  #
  media-catalog-service:
    build:
      context: ./backend/Media-Catalog-Service/
      dockerfile: Dockerfile
    container_name: media-catalog-service
    restart: unless-stopped
    expose:
      - "8080"
    env_file:
      - .env
    networks:
      - media-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/media`)"
      - "traefik.http.routers.media.entrypoints=web"
      - "traefik.http.routers.media.service=media-catalog-service"
      - "traefik.http.services.media-catalog-service.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.media-stripprefix.stripprefix.prefixes=/api/media"
      - "traefik.http.routers.media.middlewares=auth-forward@file,media-stripprefix"
  #
  # Postgres DB to store user data
  #
  auth-db:
    image: postgres:18
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - /data/auth-db:/var/lib/postgresql
    networks:
      - media-network
    ports:
      - "5432:5432" #map to host to access db from dbclients
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  #
  # Postgres DB to user collections
  #
  collection-db:
    image: postgres:18
    container_name: collection-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${COLLECTION_DB_NAME}
      POSTGRES_USER: ${COLLECTION_DB_USER}
      POSTGRES_PASSWORD: ${COLLECTION_DB_PASSWORD}
    volumes:
      - ./data/collection-db:/var/lib/postgresql
    networks:
      - media-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${COLLECTION_DB_USER} -d ${COLLECTION_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
