---
http:
  middlewares:
    #secure-headers:
      #headers:
        #frameDeny: true
        #sslRedirect: true
        #stsIncludeSubdomains: true
        #stsPreload: true
    auth-forward:
      forwardAuth:
        address: "http://auth-service:8080/verify"
        authResponseHeaders:
          - "X-User-Id"
          - "X-User-Email"
